---
title: Introduction
author: Chin Man KWAN
chapter: 1
in_context: True
knit: iheiddown::chapter_pdf
abstract: |
  In this chapter, I'll introduce how to write basic text using markdown.
  It is super simple, as you will see. You just write normal text,
  but then indicate where you want certain formatting with some very basic 'markup'.
output: iheiddown::chapter_pdf
---

\setcounter{chapter}{0}

# Introduction {#intro}

Asylum seekers, defined by Amnesty International -@amnestyinternationalRefugeesAsylumseekersMigrants2022 as individuals who are forced to flee from their home countries due to threats of persecutions and human rights violations, has become one of the most salient socio-political issues in the 21st Century, especially after the 2015 European Refugee Crisis which has led to numerous political consequences, notably the rise of anti-immigration parties in several European countries. Just as the European Refugee Crisis started to unfold in 2015, the issue of asylum seekers (or more formally, non-refoulement claimants) had not gain significant attention in Hong Kong until early 2016, after a senior Immigration Department official claimed that the city's Unified Screening Mechanism (USM) used for assessing non-refoulement applications was being abused during a TV interview and two fabricated WhatsApp audios alleging asylum seekers of committing robberies and homicides in the New Territories were propagated [@ngFramingIssueAsylum2019]. Not unseen in other countries, non-refoulement claimants are often depicted with pejorative terms which question the genuineness of their applications to seek refuge in Hong Kong from threats of tortures back in their home countries. For instance, during the months when non-refoulement claimants first attracted attention in public debate, a large proportion of headline articles in newspaper were published by two pro-Government (or pro-Beijing) newspapers which portrayed this group of population with various derogatory terms, such as being "fake refugees" who exploit the city's USM to seek illegal work or commit crimes [@ngFramingIssueAsylum2019].

The broader political context of Hong Kong as a destination of asylum seekers is that since the transferral of sovereignty from Britain to China in 1997, the city has witnessed increasing tension with its new sovereign owner. Until July 2020 when the *Hong Kong Special Administrative Region* (HKSAR) Government passed the National Security Law and the subsequent commencement of the large-scale suppression of the opposition camp such as the mass arrest of 53 pro-democracy activists in January 2021 [@bbcNationalSecurityLaw2021], protests against the authority of the HKSAR and Beijing Governments had often occurred. Apart from the annual July 1 protest since 2003, the two most prominent political movements were the 2014 Umbrella Movement and the more recent 2019 anti-extradition law protest which created considerable attention from other countries as well. In the latter protest, what started from several matches in June that altogether mobilised millions of Hongkongers to protests against a law which would have allowed fugitives in Hong Kong for being extradited to mainland China eventually evolved into months-long protests including several violent clashes between protesters and the Hong Kong police. Indeed, the political identities of both pro-Government and opposition camps manifested saliently and confronted each other during the 2019 protest. Perhaps one of the most high-profile events of the confrontation between the two camps' identities would be some protesters forcing their way into the central chamber of the city's legislature building while vandalising the HKSAR emblem and raising the former British colonial flag on the very day which was the 22nd anniversary of Hong Kong's sovereignty being transferred to China [@bbcHongKongProtesters2019].

The question that this thesis will investigate with regard to these two events is:

> Given the highly politicised nature of Hong Kong's mass media landscape as recorded by @leeChangingPoliticalEconomy2018 and the prominent role of the Chinese-language mass media in Hong Kong in framing socio-political issues, is the sentiment of news articles towards asylum seekers in Hong Kong correlated with the political affiliation of newspaper outlets?

The data to be used for investigating this question will be Chinese-language newspaper articles published in 2019 on non-refoulement claimants. The reasons for focusing on news articles from 2019 are twofold. Firstly, I would like to investigate if the publication pattern (e.g., the dominant publishing outlet on this issue and the distribution of the sentiments of the articles) of news related to asylum seekers in Hong Kong in 2019 shared any similarities compared to when the issue first became salient back in 2016. Secondly, since 2019 was marked with one of the most intense conflicts between the Government and oppositions in post-1997 Hong Kong, it would also be interesting to see if there exists pronounced difference in how non-refoulement claimants may be portrayed by media outlets from different political camps, just as how the pro-Beijing (mainly via the Hong Kong police) and opposition camps confronted each other on the streets.

## Contribution to the literature

Besides the motivation to write on this topic as mentioned in the *preface* section, this thesis also aims to make the following contributions to the literature. Starting with the literature on asylum seekers in Hong Kong, although there certainly exist numerous studies on non-refoulement claimants with various perspectives such as an anthropological approach to study their life in the city [@vecchioAsylumSeekingGlobal2014], how asylum seekers may be served for the identity construction of some local youngsters [@mathewsAsylumSeekersSymbols2018] and how Hong Kong's policy and legal apparatus marginalise this group of vulnerable population [@ngCriminalizingInnocentsSocial2020], to date there are only few studies directly related to how asylum seekers are portrayed by mass media shortly before and after the issue first drew public attention in 2016 which was an election year of the city's legislature [@ngFramingIssueAsylum2019; @ngResistanceFramingPortrayal2021]. While these two studies (one on traditional and another on online news media) offer invaluable inspiration to this thesis and are important precursors for the study on this topic, it would be beneficial to also study how news articles about asylum seekers are covered some time after the issue first gained public attention to see if the publication pattern remains consistent or not. This can help better understand if media outlets from certain political camps were likely just galvanising the issue of non-refoulement claimants for electoral gains of their camp in the short run, or they are also attempting to construct a particular framing and narrative on asylum seekers within the city which may then be used to justify policy-making positions in the long run.

This thesis also aims to contribute to the literature on the effects of different definitions of national identity on the perception of immigrants. Specifically, I am interested in whether definitions of national identities proposed by different political camps which vary their emphases on the ethnic-based or civic-based dimensions (the definitions of these dimensions will be elaborated in the *Literature Review* chapter) may lead to different attitudes towards asylum seekers as reflected by the media discourse produced by each camp. It is certainly true that Hong Kong has its own particularities which may not be applicable in other cases (for example, Hong Kong has never been a signatory of the 1951 Refugee Convention and thus is not legally bound to recognise refugees), but on a more abstract level, the definitions of Hong Kong's national identity by different political camps can be categorised according to the ethnic and civic dimensions (as discussed in next chapter), and the tension between the opposition in Hong Kong and the central government in Beijing is not completely unseen in other parts of the world where regional authorities have attempted to fight for more autonomy or even independence from the central governments (to name just a few cases, Quebec in Canada and Catalonia in Spain). Accordingly, studying the case of Hong Kong about whether a political camp's definition of national identity may be correlated to its attitude towards asylum seekers can provide indications of how national identity may play a role in affecting the attitudes towards asylum seekers in general and how the politics of asylum seeking regime may develop in regions where the degree of the central government's authority is contested in particular.

Lastly, this thesis aims to test out if automated approaches to perform sentiment analysis on textual data in Chinese language can generate reliable results. @vanatteveldtValiditySentimentAnalysis2021 note the lack of endeavours to utilise automated methods on non-English texts for sentiment analysis tasks which hampers the development of comparative research in the communication field, and yet automated sentiment analysis has the benefit of being easier to scale to larger datasets where human coding would become too time- and resource-consuming despite its high degree of validity. Although the two studies by @ngFramingIssueAsylum2019 and @ngResistanceFramingPortrayal2021 which used human coding to analyse the narrative on asylum seekers in Hong Kong by mass media between mid-2015 and mid-2016 can more thoroughly examine how non-refoulement claimants are depicted besides knowing the sentiments of the articles, this approach may gradually become very laboursome if a study was to compare the reportage of asylum seekers between newspaper outlets over the span of several years which will considerably increase the size of the document corpus. Accordingly, using the news articles from 2019 to analyse whether attitudes towards non-refoulement claimants may vary according to a newspaper's political affiliation via automated approaches can test the validity of these techniques, thereby checking whether machine-learning-based sentiment analysis is appropriate to be adopted on scaling the analysis to larger document corpora about how socio-political issues may be portrayed in Hong Kong as conditioned by certain features of the news articles or media outlets. If the results generated in this thesis via machine learning models are overall reliable, it will be worthwhile to test how such techniques may also fare in other types of policy documents such as speeches made by officials and legislators in the legislature in future research. In short, the validation of machine-learning-based methods in the context of social sciences research for Chinese text data can open up more possibilities for investigating intriguing questions.

## Outline

This thesis will proceed as follow. In section 2, I will review the literature on the theories about how the perception of national identity might affect attitudes towards immigration, how each major political camp in Hong Kong perceives the national identity of Hong Kong, and how each camp perceives asylum seekers. Section 3 explains how the hypothesis is formulated and its expected direction, how the data was collected and pre-processed, what kind of models will be used for the analysis and how the variables will be operationalised. Section 4 records the process of the data analysis from preliminary exploring the data to modelling them, presents the results and discusses the findings. Section 5 concludes this thesis and mentions the potential implications of the findings. To briefly summarise the findings, it is predicted that newspaper outlets from the pro-Beijing camp, which emphasises on the ethnic Chineseness shared among local Hong Kong citizens and mainland Chinese for constructing the national identity of Hong Kong, are indeed more likely to portray asylum seekers more negatively than non-pro-Beijing newspapers after accounting for the presence of different topics and other features of the news articles.

Before moving on, it should be mentioned that I will use the terms "asylum seekers", "refugees" and "non-refoulement claimants" interchangeably. It is true that difference exists between the definitions of asylum seekers and refugees[^1]. Nevertheless, since the above three terms are generally used to refer to the same group of population in Hong Kong who flee from their own countries to escape from threats of torture, treating these terms as synonyms in this context should better cover how this group of population is portrayed by media outlets in different political camps. In fact, scholars researching on this issue often use the terms I listed without strictly differentiating them (e.g. @vecchioAsylumSeekingGlobal2014, @ngFramingIssueAsylum2019).

[^1]: Formally speaking, *asylum seekers* refer to individuals who still have pending applications of their asylum status, whereas *refugees* refer to those who have gained recognition from the UN for being forced to flee from their countries due to threats on their personal securities [@ngCriminalizingInnocentsSocial2020].
