---
title: Literature review
author: Chin Man KWAN
chapter: 2
in_context: True
knit: iheiddown::chapter_pdf
abstract: |
  In this section I will review both the theoretical literature on how the perception of national identity may affect attitudes towards immigrants as   well as the situation of political camps and asylum seekers in Hong Kong
output: iheiddown::chapter_pdf
---

\setcounter{chapter}{1}

```{python lit_review_import_modules, include=FALSE}
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
sns.set_theme(context="paper")
```

```{python lit_review_data_import, include=FALSE}
# Asylum seekers data
asylum_seekers = pd.read_csv("data/HK_asylum_stats.csv")

# Refugees in Hong Kong data
refugee = pd.read_csv("data/refugee.csv") 
refugee = refugee.drop(columns = ["Indicator Name", "Indicator Code"]).melt(id_vars=["Country_Name", "Country_Code"], var_name="Year", value_name="refugees")
refugee["Year"] = refugee.Year.astype("int64")
refugee_hk = refugee.query("Year >= 1997 and Country_Code == 'HKG'")

# Asylum seekers by nationality in Hong Kong, circa 2021
asylum_nationality = pd.read_excel("data/asylum_nationality_2021.xlsx")
```

# Literature Review {#theory}

To understand how the different conceptions of the Hong Kong identity may affect attitude towards asylum seekers, it is important to first review the literature on how national identity may affect attitudes towards immigrants and how Chineseness may be articulated on theoretical level, as well as how political camps in Hong Kong may define the city's national identity and the situation of asylum seekers on empirical level.

## Theories

### What is national identity?

I will adopt the definition proposed by @greenfeldNationalismNationalIdentity2007, which is how an individual relates to a broader societal order called the nation and is central to modern political and social organisations. @lewin-epsteinNationalIdentityXenophobia2005 point out modern nationalism's conception that people with similar cultures (e.g. language, myths, historic territory) should congregate together as the basis of political community called the nation-state. A closely related but not identical concept to nationalism is ethnicity, defined by @varshneyEthnicityEthnicConflict2007 as sense of belonging shared by a group in ancestry, language, history, culture and/or history. Whereas nations have their own territory-based political authority, this is not necessarily the case for ethnic groups.

@greenfeldNationalismNationalIdentity2007 also elaborate on some peculiar features of nationalism. For instance, the secular world where nations are located is deemed the most important to human beings and their life. But the more well-known characteristic is that the world is perceived to be divided into distinct communities (i.e. nations) occupying their own territories, and each member of "the people" within a nation is treated as equal to one another. It is also "the people" who ultimately control political legitimacy and authority. These features together contribute to two fundamental implications. Socially, the fact that nationals are considered as being equal and that status is achieved instead of ascribed promotes social mobility. Politically, nationalism has made modern (nation-)states "impersonal" (p.261) because whoever holds the government office does not affect whatsoever the nation-state's existence and legitimacy which ultimately rest in popular sovereignty [@greenfeldNationalismNationalIdentity2007]. But for cultures that had been existing long before nationalism's entry into these societies, the constructions of novel national identities may often rebrand pre-existing cultures despite the latter's internal heterogeneity, of which Chineseness is an example which I will look into later.

Lastly, @greenfeldNationalismNationalIdentity2007 propose a typology of nationalism with two criteria. The first one is how the nation-state relates itself to its members, from the individualist end of treating a nation as merely a massive group of individuals to the collectivist end of which individuals are subservient to the nation. The other criterion is the well-known "ethnic" versus "civic" dimension which is extensively studied, including its relation with the perception towards immigrants which I will discuss later. In general, ethnic nationalism defines a nation's members based on ascriptive and rather objective standards such as descent, language and customs which are largely decided at birth, whereas civic nationalism focuses less on the members' cultural backgrounds than their voluntary allegiance to a political community and its legal institutions within a political territory [@greenfeldNationalismNationalIdentity2007; @lecoursEthnicCivicNationalism2000; @lewin-epsteinNationalIdentityXenophobia2005; @heathBritishNationalIdentity2005].

A note on the ethnic-civic dimension is that these two aspects are not mutually exclusive since @medranoNationalismCitizenshipImmigration2005 highlight that nationalism in one country can often incorporate both civic and ethnic features, which is quite frequently observed from empirical. Accordingly, scholars often create other dimensions of describing nationalism theoretically. For example, @hjermNationalIdentityComparison1998 proposes to additionally gauge whether identifications with ethnic and civic features of nationalism are high ("multiple national identity") or low ("pluralist") at the same time (p. 453). Meanwhile, some scholars prefer more fine-grained categories of citizenship criteria. @medranoNationCitizenshipImmigration2005 breaks the ethnic and civic dimensions further into five categories while describing the importance of criteria for citizenship perceived by the Spanish population, namely (p.137),

> -   the civic dimension being broken down into:
>
>     -   Pure republican criteria: Long-term residence, feeling of belonging, and being a citizen of that state
>
>     -   Political criteria: Respect for laws and political institutions
>
> -   and the ethnic dimension into:
>
>     -   Territorial criteria: Place of birth
>     -   Cultural criteria: Language, religion, customs and traditions and
>     -   Descent

### Impact of conceptions of national identity on attitudes towards immigrants

Perhaps one of the most prominent consequences of how national identity is perceived by individuals is their attitudes towards immigrants. This is because national identity simultaneously defines members and outsiders of a nation [@hjermNationalIdentityComparison1998; @lewin-epsteinNationalIdentityXenophobia2005; @heathBritishNationalIdentity2005]. For simplicity's sake, I will mainly focus on how tendency towards defining national identity in ethnic and civic terms may be correlated with perceptions towards immigrants.

To begin with, although it is generally agreed that characteristics used to demarcate membership in a nation can be classified as ethnic- or civic-based on a macro-level, additional categories are often needed to capture the general patterns of how national identity is defined within a country and how such definitions may affect citizen's attitudes towards immigrants. A potential reason for such a need is that although individuals may hold a rather "pure" civic conception of identity mostly devoid of ethnic components, it is quite unlikely that individuals would consider ethnic components as standalone enough for constituting a nation's citizenship without any civic components. Indeed, empirical evidence from @hjermNationalIdentityComparison1998, @heathBritishNationalIdentity2005 and @medranoNationCitizenshipImmigration2005 demonstrate that it is very rare for individuals to perceive national identity solely in ethnic terms, since those who attribute importance to ethnic-based components are also likely to do so to civic-based ones simultaneously. Often, scholars may even challenge the ethnic-civic-dimension in classifying the perception of national identity and propose alternative schema. Drawing on the Weberian idea of social closure which measures the number of obstacles imposed by a group for outsiders to join, @medranoNationCitizenshipImmigration2005 proposes the "postnationalist" versus "credentialist" (p.136) dimension which differentiates how restrictive people consider acquiring citizenship to their nation should be. Specifically, postnationalists impose few limits on foreigners to become citizens, whereas credentialists require a long list of criteria being fulfilled. That said, even though there exist multiple and equally valid alternatives for categorising how national identity may be defined, the ethnic-vs-civic dimension is quite broadly applicable to explain the typologies of nationalism in countries with some modifications and thus is a decent starting point.

As for the potential impact of national identity on attitudes towards immigrants, the literature tends to agree that the more an individual holds ethnic-based criteria of membership in a nation, the more likely (s)he will be averse against immigrants (i.e. xenophobic). It seems that the effect of ethnic-based national identity conception on xenophobic attitudes is consistent across different immigration policy regimes differing on the ease of naturalisation and the mode of integration. @hjermNationalIdentityComparison1998 discovers that despite Germany, Australia and Sweden having considerably different immigration policy regimes, individuals who agree that having both ethnic and civic characteristics are crucial for being a member of their nations are more likely to be xenophobic than others who only use civic components to demarcate nationhood or ascribe little importance to nationalism. Similar findings are observed by @heathBritishNationalIdentity2005 in the UK context, as British who place more emphasis on ethnic-based nationhood criteria will be more inclined to approve reducing immigrants inflows and more stringent measures against illegal immigrants. Interestingly, Heath also discovers that after controlling for how national identity is conceived, the extent to which an individual is attached to the nation is no longer significant in affecting his/her attitude towards immigrants.

In some cases, however, the effect of national identity on perceptions towards immigrants may be less due to whether individuals hold ethnic-based definitions of national identity than how many criteria individuals deem to be indispensable for obtaining a nationality. For instance, @medranoNationCitizenshipImmigration2005 argues that even though there is an association between including ethnic-based (or in his terminology "ethno-biological republican") (p.148) criteria for obtaining Spanish citizenship and holding negative attitudes towards immigrants, it is ultimately how many criteria a Spanish regards as important for being a Spanish citizen that better predicts attitudes towards immigrants, evidenced by the stronger correlation between these two items found in his study.

Furthermore, depending on the ethnic composition of a nation-state, not only may different ethnic groups have their own definitions of what constitute to the ethnic and civic components of national identity, but also the relations between perceptions of national identity and attitudes towards immigrants may go into rather unexpected directions. @lewin-epsteinNationalIdentityXenophobia2005 discover that in the Israeli society which can be broadly separated into three ethnic groups (namely, veterans Jews who have lived in Israel for a long time, Olim who are recent Jewish immigrants from former Soviet Union regions, and ethnic Arabs citizens in Israel), there are only moderate similarities in terms of which components should be included into the ethnic and civic dimensions of national identity, as they disagree on whether the ability to speak Hebrew and whether being born in Israel should be labelled as ethnic or civic components. Moreover, contrary to the expectation in the literature, veteran Jews who consider the Israeli nationality as more ethnic-based are actually *less* averse towards immigrants, possibly because they are likely to perceive immigrants as mostly overseas Jews who share the same ethnicity [@lewin-epsteinNationalIdentityXenophobia2005]. Nevertheless, the surprising case of Israel is likely to be more due to its specific socio-political context rather the theoretical pitfalls of how ethnic-based conceptions of national identity may be related to xenophobia per se.

### Chineseness in Hong Kong

Given over 90% of the population being ethnically Han Chinese by 2016 [@home_affairs_departmentDemographicsEthnicGroups2018] and also large-scale pro-democracy political movements in the 2010s challenging the authority of the HKSAR and Chinese Governments (particularly the 2014 Umbrella Movement and the 2019 Anti-Extradition Law Protest), Chineseness indeed occupies a salient position on the discourse of the Hong Kong identity. It is then important to understand what Chineseness may mean in Hong Kong, a city under British colonial rule for over a century until 1997.

Although Chineseness is usually connoted with a homogeneous image of a group of people with the same ethnic origin, place of residence or cultural characteristics (e.g. language, customs etc.), @chunFuckChinesenessAmbiguities1996 problematises this conception not least because expressions used to describe different aspects of Chineseness actually contains heterogeneity. For example, despite the contemporary use of Han Chinese to denote ethnic homogeneity, people under the Han empire were anything but ethnically homogeneous. It was not until the 1911 Revolution then China became a nation inhabited by the single ethnic group called *Zhonghua Minzu*, and a homogeneous national culture was accordingly invented and legitimised by the state. The efforts to articulate a Chinese national identity continued after the foundation of the People's Republic of China (PRC) in 1949, as both the Kuomingtang (KMT) regime in Taiwan and the PRC (after the Maoist period) extensively used Chinese history, political ideology and/or values to construct their national cultures and identities to claim themselves being the orthodox Chinese nation.

Whereas Chineseness was constructed by Chinese regimes holding political authority in Taiwan and mainland China, Chineseness manifested quite differently in Hong Kong where it was a Chinese society ruled by the British Government before 1997. According to @chunFuckChinesenessAmbiguities1996 , most inhabitants in Hong Kong had identified as Chinese until the establishment of the PRC in 1949. @soMakingHongKong2015 also mentions that before 1949, ethnic Chinese in Hong Kong did not intend to permanently reside in the city and identified with the broader Chinese nation, evidenced by their participation in the anti-colonial Hong Kong-Canton general strikes in the 1920s. When the Chinese Communist Party (CCP) took power in 1949, however, the identity of ethnic Chinese in Hong Kong started to gradually depart from that on the maindland. As Hong Kong had become the venue to the KMT and the CCP's contest of the Chinese identity in the 1950s, the British Government then attempted to pull Hong Kong away from this nationalist conflict by actively promoting economic transformation from a Chinese entrepot to exported-oriented economy, and the colonial government started to create a new Hong Kong identity to further distance the citizens from Chinese nationalism following the outbreak of leftist riots in the late 1960s [@chunFuckChinesenessAmbiguities1996; @soMakingHongKong2015] .

With intellectuals in Hong Kong paying more and more attention to local instead of Chinese affairs and the huge influx of illegal immigrants from China in the 1970s, the conflict between the old and newly arrived residents eventually led to the rise of a Hongkonger identity [@soMakingHongKong2015] . By mid-1980s, Hong Kong eventually developed its own culture which was indifferent to politics while also fusing habits from Chinese and Western cultures together [@chunFuckChinesenessAmbiguities1996] . As the transfer of the city's sovereignty approached in the 1980s, however, the Hong Kong identity became more complicated. On one hand, the investment opportunities in and relocation of factories to mainland China due to the reform and opening up policy helped resurge Chinese nationalism among Hong Kong business elites and working class who married mainland Chinese [@soMakingHongKong2015] . Meanwhile, the uncertainty associated with the transition of sovereignty, especially after the Tiananmen Massacre in 1989, caused the public to be more conscious of values respected in Hong Kong such as the rule of law and civil liberties and thus increased their perceived difference between Hong Kong and China [@soMakingHongKong2015; @fongOneCountryTwo2017; @linMakeChinaGreat2021] .

Amidst the fear of Hong Kong losing its unique after the handover to China in the 1990s, the *One Country, Two Systems* (OCTS) framework which stipulates Hong Kong's autonomy and continuity of the capitalist system for 50 years was accordingly put in place to secure confidence of the public regarding the handover [@soMakingHongKong2015; @fongOneCountryTwo2017] . Indeed, the first decade after 1997, @soMakingHongKong2015 and @fongOneCountryTwo2017 report that overall more and more Hongkongers identified as Chinese despite Beijing's increasing intervention (more on this later) after the mass protest against Article 23 in 2003, and such sentiment peaked in 2008 when China was the host of that year's Olympic Games. But the Hong Kong identity has once again become prominent since 2009 as Hongkongers become aware of Beijing's increasing political interference and the social disruption brought by the large influx of mainland Chinese, and @fongOneCountryTwo2017 highlights how the Hong Kong identity has emerged in a mentality of resisting against "invaders" from the mainland during the period (p.19).

In short, Chineseness as how closely Hong Kong people identify themselves as members of the Chinese nation have evolved throughout the course of history, and one could argue that following the transferral of Hong Kong's sovereignty to China, the Chineseness of Hong Kong identity has become more and more contested. This phenomenon is best reflected by how each prominent political camp in Hong Kong envisions the Hong Kong identity.

## Empirics

### How do different political camps in Hong Kong perceive national identity?

With Hong Kong's major political cleavage being demarcated by the city's relations with Beijing and the pace of democratisation, different political camps may adopt their own vision of what Hong Kong's national identity should be. Indeed, @lecoursEthnicCivicNationalism2000 highlights the importance of political goals in affecting how political actors with different ideologies on a region's relations with the national government may formulate national identity through the case study of Quebec. He argues that the secessionist Parti Quebecois (PQ) is motivated to adopt an ethnic-based nationalism which emphasises on French being the Quebecois' mother tongue because the party needs a more salient cultural marker to convince Quebecois that they are indeed qualitatively different from the Anglophone Canada and thus warrants a separate nation. By contrast, since the autonomist Parti Liberal du Quebec's (PLQ) goal is to demand more political autonomy instead of secession, the party can adopt more civic-based framing of nationalism which does not restrict membership to the Quebecois society exclusively to Francophones while not explicitly relying on ethnic markers to distinguish between Quebecois and Canadians.

In the following paragraphs, I will discuss the political goals of the three prominent political camps in Hong Kong regarding the city's political regime and relations with the Beijing Government, namely, the pro-Beijing camp, the pro-Democracy camp and the newly arising localist camp in the 2010s, and how their political goals may affect their articulation of Hong Kong's national identity.

#### The pro-Beijing camp

As the politically conservative force governing Hong Kong, the pro-Beijing camp's objective can be summarised as legitimising China's sovereignty over the city and protecting the political interests of China. Members of the camp include the HKSAR Government itself, political parties and societal actors who lean towards the Beijing Government etc. Perhaps the most prominent manoeuvre by the pro-Beijing camp to achieve the above objective is counteracting against demands for more rapid democratisation in both the executive and legislative branches to prevent the opposition from gaining control over the political institutions [@maPoliticalPartiesElections2012] .

Apart from controlling high-level political institutions in the HKSAR, the pro-Beijing also invests in efforts to foster patriotism towards China in different societal sectors, of which education is one. Bottom up endeavours to instil the Chinese identity into students' minds are organising trips to China as well as pedagogy of pro-China ideologies and Chinese cultures, by pro-Beijing schools and regular schools receiving sponsorship from the Government or pro-Beijing actors, whereas top-down endeavours from the Government mainly revolves around policies on national education such as teaching Putonghua in primary school since 1998, encouraging schools to raise the Chinese flag and sing the Chinese anthem in significant occasions and the failed attempt to make national education itself a mandatory subject which avoids discussion on sensitive issues in 2012 [@lauStateFormationEducation2013; @fongOneCountryTwo2017] . The pro-Beijing camp also sets up support organisations in communities for electoral mobilisation, as @lohUndergroundFrontChinese2010 and @fongOneCountryTwo2017 out how the largest pro-Beijing parties in Hong Kong have numerous subsidiaries grassroots organisations which can serve to mobilise for votes during elections under the coordination of the Liaison Office (LOCPG), and @fongInbetweenLiberalAuthoritarianism2017 reports an alleged vote-rigging incident in 2015 during which pro-Beijing-affiliated elderly homes were spotted sending elderlies, often of low cognitive abilities, to cast their votes.

With the pro-Beijing camp's goal of securing the ultimate authority and sovereignty of the Beijing Government over the HKSAR, its vision on how the identity of Hong Kong should be is then closely intertwined with the Chinese identity. In other words, pro-Beijing forces view the Chinese and Hong Kong identities as a whole in which Hong Kong is subordinate to the Chinese nation, and identification with the Chinese nation is translated into support towards the incumbent PRC regime, which self-proclaims as the "vanguard of the Chinese people and the Chinese nation" [@FullTextConstitution2017] . Indeed, @linMakeChinaGreat2021 argue that at least during 2012-19, the HKSAR government primarily portrays the Chineseness of Hong Kong citizens in an essentialist and narrow ethnic-based manner which emphasises on the shared biological inheritance from the ancient Peking Man between Hong Kong citizens and mainland Chinese while downplaying other aspects such as values, cultural heritage and lifestyle. For instance, former Chief Executive CY Leung and pro-Beijing poltician Ronny Tong claimed that Hong Kong citizens were obliged to identify themselves as Chinese due to their ascribed biological similarities with mainland Chinese. Ethnic markers were also co-mentioned while HKSAR officials were describing the PRC, as former Chief Secretary Matthew Cheung stated that he was proud as "a son of the Chinese" while witnessing the progress made by mainland China [@linMakeChinaGreat2021] (p.914).

This view echoes with that held by the Beijing Government, as Chinese President Xi Jinping once claimed that Hong Kong's fate was closely linked to mainland China, and the city was crucial for achieving the Chinese dream [@linMakeChinaGreat2021] . In essence, as the ruling government of post-1997 Hong Kong is now under the sovereignty of the PRC, it is likely that the HKSAR Government and its political ally, the pro-Beijing camp, actively promote Chineseness as an ethnic feature that both Hong Kong citizens and mainland Chinese share closely to realign the Hong Kong identity, which is deemed to had developed separately in British Hong Kong [@chunFuckChinesenessAmbiguities1996; @soMakingHongKong2015] , under the umbrella of Chinese so that Beijing could exert more control over the city's ideology. By contrast, civic values are less salient in the official discourse in promoting Chineseness in Hong Kong (except for the value of patriotism which is ultimately another manifestation of the ethnic conception of Chineseness), but are often used by the pro-Democracy camp to portray Hong Kong's distinct (but **not** independent) identity from mainland China.

#### The pro-Democracy camp (or pan-democrats)

According to @maPoliticalPartiesElections2012 , even though several pro-democracy political groups were founded in the 1980s after the commencement of the city's democratisation and elections as well as the signing of the Sino-British Joint Declaration in 1984, it was not until the late 1980s when these groups congregated together for better mobilisation power in large-scale political movements, especially during the 1989 Tiananmen Movement when the Alliance for the Support of the Patriotic and Democratic Movement (ASPDMC) was formed to support students protesting for democracy in Beijing. Shortly afterwards, the first pro-democracy party, *the United Democrats of Hong Kong* (the predecessor of the present Democratic Party) was created in 1990 for next year's first direct election in the legislature [@maPoliticalPartiesElections2012] . After the handover in 1997, the pro-democracy camp remains as one of the significant political forces in the HKSAR, including the provision of an alternative perception of the Hong Kong identity vis-a-vis the official rhetoric.

Compared to the pro-Beijing camp which considers protecting the interests of the Chinese nation (currently under the PRC regime) as paramount over other concerns, the pro-democracy camp instead prioritise values such as the rule of law and civil liberties which are regarded to be constitutive to the civic elements of Hong Kong's identity [@kwanRiseCivicNationalism2016] . This is evidenced by the pro-democracy camp deeming the Article 23 legislation back in 2003 as contravening personal freedom under the pretext of national security and thus openly opposed to and organised the 1 July rally against the law's promulgation [@maPoliticalPartiesElections2012] , and the camp also supported the Occupy Central Movement (a precursor to the 2014 Umbrella Movement) to protest against Beijing's proposal of only allowing pre-approved candidates to run for Chief Executive elections in August 2014 as violating democratic principles of universal suffrage [@kwanRiseCivicNationalism2016] . It can thus be argued that the pro-Democracy camp puts more importance on protecting the civic values that they deem crucial for the identity of Hong Kong, even if this means often clashing with the interests of Beijing.

When it comes to identifying which nation Hong Kong belongs to, however, it should be note that the pro-democracy camp in general still identify themselves as Chinese, as @kwongGrowthLocalismHong2016 states that especially for the older generation pro-democratic politicians, they are in favour of Hong Kong's sovereignty being transferred from Britain to China in 1997, and they claim to share affinity with China's history, culture and ethnicity despite opposing the CCP's one-party dictatorship. In fact, the identification with the Chinese nation by the pro-democracy camp is well-inscribed in the manifesto of the largest and most historic pro-democracy party, *the Democratic Party*, as the very first article clearly claims that "Hong Kong is an indivisible part of China" [@Manifesto2021] . The pro-democracy camp's identification as members of the Chinese nation may very well explain how they contextualise Hong Kong's democratisation movement and why they do not think Hong Kong identity is independent of the Chinese one. @kwongGrowthLocalismHong2016 mentions that the pro-Democracy camp generally considers Hong Kong's democratisation as integral to that of mainland China, and the annual candlelight vigil by the ASPDMC is a totem of this mentality since some organisers perceive a democratic China, if realised, might subsequently bring democracy to the city as well.

Admittedly, the pro-democracy camp attempted to appeal to localist supporters when the ideology gained huge popularity around the time of the 2016 Legislative Council election, such as calling for the right of self-determination for Hong Kong [@kaedingRiseLocalismHong2017; @fongOneCountryTwo2017] . Nevertheless, this does not mean the pro-democracy camp giving up on caring about political issues in China while relating them to the situation in Hong Kong. Even in the 2021 Tiananmen Massacre candlelight vigil, the ASPDMC stated that Hong Kong people shared "a common fate with those oppressed and deprived of freedom in China", and the organisation would struggle until both Hong Kong and China became democratic [ASPDMC -@Theme32ndAnni2021] .

In short, the pro-democracy camp considers civic values in Hong Kong such as the rule of law and civil liberties to be constituting to the distinctiveness of Hong Kong and is averse towards Beijing's political interventions which often run against these values. Nevertheless, the camp still regards Hong Kong as belonging to the same nation with mainland China and is even willing to help their Chinese compatriots in political movements which advocate freedom and democracy. The geographical scope of how wide Hong Kong's political movement to democratisation should concern, then, is partly what makes the localist camp different from the pro-democracy camp even though both favour a democratic regime in Hong Kong.

#### The localist camp

Broadly speaking, the rise of localism as a third prominent political ideology in the 2010s was due to both the increasing integration with mainland China both politically and socio-economically as well as the perceived incompetence of the pro-Democracy camp to push forward substantive democratisation in Hong Kong. Although the term "localist camp" in reality represents an aggregation of groups which vary considerably in choosing violent or non-violent means of resisting against the Beijing Government, whether Hong Kong should abandon OCTS and pursue independence, and are much less coordinated in their actions compared to the pro-Beijing and pro-democracy camps, organisations belonging to this camp hold strong averse sentiment against China **both** in terms of the PRC regime and mainland Chinese who are deemed to be depriving the locals of already scarce public resources or disrupting the way of life of ordinary Hong Kong citizens, and they [@kwongGrowthLocalismHong2016] . The first substantive discourse to materialise localism as a political ideology was "Hong Kong as a city-state" published in 2011 by scholar *Chin Wan-kan which*, among many other ideas, advocates separating the integration between Hong Kong and mainland China as well as prioritising the needs of Hongkongers [@soMakingHongKong2015] . The following paragraphs will outline how the rise of localism can be treated as a backlash against both long-existing political camps in Hong Kong while also exploring how localists perceive Hong Kong's national identity.

Starting with the so-called "China factor", the localist camp obviously rejects the pro-Beijing camp's (and the Chinese Government) claim that Hong Kong's identity should be treated as one with that of Chinese. @fongOneCountryTwo2017 illustrates how the China factor has facilitated the rise of localism under the framework of "state-building" versus "peripheral" nationalism (p.2), where Hong Kong is attempting to consolidate its unique identity against Beijing's incorporation of the city into the hegemonic national culture. Specifically, after 500,000 Hongkongers had rallied against the Article 23 legislation in 2003, Beijing then started to increase its interventions in multiple areas, such as asserting that its authority overrides the city's autonomy, sponsoring pro-Beijing candidates during elections and fostering further economic integration between Hong Kong and China in finance, tourism and trade.[@soMakingHongKong2015; @fongOneCountryTwo2017] . In turn, the high proportion of respondents in a 2016 survey identifying themselves as Hongkongese amidst the foundings of more radical localist organisations which aspire to make Hong Kong a separate nation can be evidence of how the PRC's attempts to assimilate Hong Kong into the hegemonic Chinese identity has risen the consciousness of Hong Kong people about their uniqueness vis-a-vis China and thus foster the increasing popularity of localism [@fongOneCountryTwo2017] . Apart from Chin's foundational discourse on localism as mentioned before, overt advocacy of Hong Kong becoming an independent nation from China is often proposed by some localist organisations, most signified by the establishment of the disbanded *Hong Kong National Party* in 2016 by Andy Chan which aimed to build a "Hong Kong Republic" [@kaedingRiseLocalismHong2017] (p.165). Some organisations even dare openly insult the PRC to challenge its authority and legitimacy, as two former legislators from the self-determination-advocating *Youngspiration* had taken their office oaths by pronouncing "China" derogatorily in 2016, which caused them to be disqualified from their seats shortly afterwards [@kaedingRiseLocalismHong2017] .

Due to the localist camp's dissociation of Hong Kong with mainland China concerning both Beijing's assimilation and which nation Hong Kong belongs to, they also reject the pro-Democracy camp's idea that political development of Hong Kong should be linked to that of China. In effect, the indifference of the localist camp to China's political situation is largely due to the "transition fatigue" which witnesses increasing dissatisfaction with the traditional pro-democracy camp has started to accumulate due to the lack of substantive progress in democratisation by 2008 [@kwongGrowthLocalismHong2016] (p.63). The Democratic Party's decision to negotiate with the Beijing Government for the political reform package and its subsequent support in May 2010 created profound division within the pro-democracy camp as certain parties believed that more radical measures were needed to fend off Beijing's interference into the city, but the more significant turning point for localism to gain its popularity was the 2014 Umbrella Movement when some youngsters blamed the pro-democracy camp for the Movement's failure [@kwongGrowthLocalismHong2016; @kwanRiseCivicNationalism2016] .

The disagreement between the pro-democracy and localist camp lies less in what kinds of values Hong Kong should uphold (as both camps aim at fighting for democracy and autonomy from Beijing) than whether Hong Kong should involve in China's democratisation. Specifically, the pro-democracy camp's insistence on Hong Kong's responsibility to help build democracy in China is met with strong criticism from the localists, who consider that Hong Kong should focus only on its political development since binding Hong Kong's future to a democratic China would hamper the city's own interests [@kwongGrowthLocalismHong2016; @kwanRiseCivicNationalism2016] . Thus, the different conceptions of which nation Hong Kong belongs to between the two camps and how much Hong Kong should dissociate from China have caused both camps to have rather contentious relations, as some pan-democrats also consider the localist camp's hostility towards mainland Chinese as xenophobic [@kwongGrowthLocalismHong2016] .

In short, the localist camp does not just treat the Hong Kong identity as distinctive but ultimately belongs to the Chinese nation like the pro-democracy camp. Instead, Hong Kong is a separate political entity that should avoid close integration with mainland China in order to protect its own interests. This causes the localist camp to become a third force in Hong Kong's political arena in the 2010s confronting against both the pro-Beijing and pro-Democracy camps.

Before moving onto hypothesising how the three camp's different views on Hong Kong's national identity may impact their views on asylum seekers within the city, table 2.1 summarises how they differ on the vision of the Hong-Kong-China relations.

+-------------------------------------------------+---------------------------------------------------+------------------------------------------------------------------+-----------------------------------------------------------------------------+
|                                                 | Pro-Beijing camp                                  | Pro-Democracy camp                                               | Localist camp                                                               |
+-------------------------------------------------+---------------------------------------------------+------------------------------------------------------------------+-----------------------------------------------------------------------------+
| The nation that Hong Kong belongs to            | China                                             | China                                                            | Hong Kong                                                                   |
+-------------------------------------------------+---------------------------------------------------+------------------------------------------------------------------+-----------------------------------------------------------------------------+
| Attitude towards political development in China | Political ally of the ruling PRC                  | Opposes one-party rule of the CCP, sympathetic to Chinese people | Indifference, only focuses on Hong Kong's situation                         |
+-------------------------------------------------+---------------------------------------------------+------------------------------------------------------------------+-----------------------------------------------------------------------------+
| Prioritised political values                    | Patriotism and nationalism over individual rights | civil liberties, the rule of law and political autonomy          | those of the pro-democracy camp **plus** prioritising Hong Kong's interests |
+-------------------------------------------------+---------------------------------------------------+------------------------------------------------------------------+-----------------------------------------------------------------------------+
| Means of contention                             | N/A (as an ally of the Government)                | Non-violent                                                      | Both violent and non-violent                                                |
+-------------------------------------------------+---------------------------------------------------+------------------------------------------------------------------+-----------------------------------------------------------------------------+
| Degree of within-camp coordination              | Strong                                            | Moderate                                                         | Weak                                                                        |
+-------------------------------------------------+---------------------------------------------------+------------------------------------------------------------------+-----------------------------------------------------------------------------+

: Comparison of the three camps on key dimensions of Hong-Kong-China relations

### Asylum seekers in Hong Kong

#### Hong Kong's policy regime

Regarding the legal framework and policies of assessing asylum claims and refugee recognition, the Hong Kong Government has a strong position of not making the city a destination for refugee resettlement. Although Hong Kong is a signatory of the 1992 United Nations Conventions Against Torture (UNCAT) which requires the Government to temporarily house asylum seekers and process torture-related asylum applications, the city has never signed the 1951 Refugee Convention and thus has no legal obligations to permanently resettle asylum seekers and refugees within its territory [@ngCriminalizingInnocentsSocial2020] . This remains true even after the implementation of the Unified Screening Mechanism (USM) in 2014 which made the Government become the sole handler of all the non-refoulement claims, including those which had been previously handled by the UNHCR for refugee status [@ngCriminalizingInnocentsSocial2020; @UnifiedScreeningMechanism2021] . Instead, the Government reiterates its lack of intention of determining individuals' refugee status and allowing refugees to permanently settle in the city, while also claiming that the recognition and resettlement of refugees should still be referred to the UNHCR "in accordance with its mandate" [@MakingClaimNonrefoulement2021] , even though the UN agency states on its website that it would no longer process new refugee and asylum claims following the implementation of the USM [@UnifiedScreeningMechanism2021] . Simply put, the official institutions responsible for assessing asylum applications in Hong Kong hardly have intention of making the city a destination of permanent resettlement for individuals fleeing from their countries because of persecutions.

Even if the HKSAR Government is obliged to adjudicate non-refoulement applications as per the UNCAT, the legal and social status of the asylum seekers are quite precarious while awaiting their application results. To begin with, individuals must wait until their visas expire in order to be eligible for non-refoulement applications and then have to report regularly to the Immigration Department [@UnifiedScreeningMechanism2021] , an arrangement that @ngCriminalizingInnocentsSocial2020 considers as the Government's attempt to exclude asylum seekers from the rights granted to legal residents in the city (e.g. working, ) and receiving welfare supports through criminalisation. Furthermore, the Immigration Department has the final authority to prosecute the asylum seekers for having illegally overstayed beyond the validity of their visas, and officials frequently call these populations as *illegal immigrants* (often with racial labels) [@ngCriminalizingInnocentsSocial2020] . Coupled with the Government's refusal to recognise and resettle refugees in its territory, the institutional framework of asylum seeking in Hong Kong can thus be described as unwelcoming towards those who are fleeing from persecutions in their countries of origin, since these applicants not only have to first become illegal immigrants for eligibility to request non-refoulement, but also they are under the constant threat of being charged for their immigration status.

```{python, fig.cap="Number of non-refoulement claim cases (left) and refugees (right) in Hong Kong"}
fig, axes = plt.subplots(1, 2)

# non-refoulement claimants
sns.lineplot(x="Year", y="Cases", data=asylum_seekers, linestyle = "dashed", label="New cases", alpha=.7, ax=axes[0])
sns.lineplot(x="Year", y="Outstanding(Cumulative)", data=asylum_seekers, linestyle = "dashdot", label="Outstanding cases", color = "tab:orange", alpha=.7, ax=axes[0])
axes[0].set(ylabel="Count", title='Number of non-refoulement claimants (2005-21)', xticks=np.arange(2005, 2022, 2))

# refugees
sns.lineplot(x="Year", y="refugees", data=refugee_hk, linestyle = ":", color="black", ax=axes[1])
axes[1].set(ylabel="Count", title='Number of refugees (1997-2020)', xticks=np.arange(1997, 2021, 3))

# global setup
plt.tight_layout()
plt.show()
plt.clf()
```

The HKSAR Government's unwelcoming stance towards asylum seekers and refugees is likely to be one of the major reasons for the low numbers of non-refoulement claims and refugees in the city since 2005. For instance, the left plot in figure 2.1 [@EnforcementStatisticsNonrefoulement2021] shows that the number of *new* non-refoulement claims submitted each year from 2005 to 2021 on average was lower than 4000, and the sudden rise of new applications to around 9000 instances in 2014 was more due to the implementation of the USM requiring the Government to also assess claims previously handled by the UNHCR than the commencement of a more liberal asylum-seeking regime [@EnforcementStatisticsNonrefoulement2021] . Likewise, the number of *outstanding* non-refoulement cases by year during the same period generally surpassed that of new cases except from 2018, a few years after the USM had been implemented. By 2018, non-refoulement claimants constituted to a mere 0.2% of Hong Kong's total population of over 7 million, a figure considerably smaller when compared to a total of 3.5 million refugees in Asia as @ngCriminalizingInnocentsSocial2020 contrasts. The right plot in figure 2.1 [@RefugeePopulationCountry2021] shows how the number of *refugees* in Hong Kong has dramatically reduced to no more than 250 persons each year (save for 2020) since 2007 after the Government had closed the last refugee camp hosting Vietnamese who fled from the Vietnam War in the 1970s [@ngCriminalizingInnocentsSocial2020] . Lastly, figure 2.2 [@EnforcementStatisticsNonrefoulement2021] indicates the nationalities of non-refoulement claimants, who mostly are from South and Southeast Asia, with a few from Africa as well. One particularly interesting insight from this graph is that despite the frequent racial labelling of non-refoulement claimants as South Asians by some media outlets [@ngFramingIssueAsylum2019] , it is actually **Southeast Asians** who constitute the largest proportion of non-refoulement claimants.

```{python, fig.cap="Number of non-refoulement claimants by nationality in 2021"}
asylum_nationality.sort_values("Number of claimants", inplace=True, ascending=False)
sns.barplot(y="Nationality", x="Number of claimants", data=asylum_nationality, color="tab:blue")
plt.gca().set(xlabel="Number of claimants", ylabel="")
plt.tight_layout()
plt.show()
plt.clf()
```

#### Responses by political camps

Given the extremely small number of non-refoulement claimants, the issue of asylum seeking regime in Hong Kong hadn't gained much attention until early 2016, after a senior Immigration Department official's accusation of the USM being abused during a TV interview in October 2015 and the subsequent propagation of two fabricated WhatsApp audios alleging asylum seekers as perpetrators of robberies and homicides in the New Territories district [@ngFramingIssueAsylum2019] . Soon afterwards, coverage of asylum seekers by newspaper media has increased, with two pro-Beijing newspapers named *The Sun* (which ceased publication in April 2016) and *Oriental Daily* contributing to the largest proportion of articles which depict this group of vulnerable population as a source of social problems (e.g. committing crimes) which warrant stringent measures like detention camps as solutions [@ngFramingIssueAsylum2019] .

Different opinions of how the Government should deal with the asylum seekers in the political debate could also be classified according to political camps at the same time. On one side, echoing with the HKSAR Government's already restrictive policies for assessing non-refoulement claims, pro-Beijing camp politicians also create narratives that non-refoulement claimants and asylum seekers are anything but genuine in the legislature. For instance, less than a year after asylum seekers had gained salience in public debate, legislator Holden Chow submitted a motion in November 2016 under the banner of "combating bogus refugees" who, among other sins, were working illegally and/or committing crimes while calling for the revision of the USM and carrying out measures against illegal immigrants adopted by other countries [@yuenProBeijingLawmakerSubmits2016] . Some pro-Beijing parties also reach out to the public to sway the latter's opinion, such as the DAB[^1] setting up a booth in the ethnic-minority-concentrated Tsim Sha Tsui district to hand out pamphlets about measures against "fake refugees" [@cheungDABPartySets2016] . Perhaps the most dramatic proposal of dealing with the so-called "fake refugee" issue by the pro-Beijing camp was the former Chief Executive *CY Leung's* suggestion to withdraw from the UNCAT in 2016 so that Hong Kong would not be obliged to assess non-refoulement claims anymore [@ngFramingIssueAsylum2019] . Coupled with the high frequency of pro-Beijing media outlets in pejoratively portraying asylum seekers in Hong Kong as mentioned earlier, the pro-Beijing camp promotes an unwelcoming rhetoric against asylum seekers that is consistent with the Government's refusal to permanently resettle refugees and asylum seekers.

[^1]: Abbreviation of the Democratic Alliance for the Betterment and Progress of Hong Kong.

By contrast, the pro-democracy camp is less hostile towards non-refoulement claimants and even advocates better treatment of these vulnerable individuals. When Holden Chow's motion was tabled for voting in the legislature in December 2016, it was barely rejected due to the pro-democracy camp's opposition of Chow's motion as "hypocrisy and discrimination in disguise" by indiscriminatingly applying the proposed "draconian measures" on all asylum seekers [@chengLegislatureRejectsLawmaker2016] . Among all pro-democracy legislators, Dr Fernando Cheung was perhaps the most vocal in fighting for better treatments of asylum seekers in Hong Kong, as he met with non-refoulement claimants directly on several occasions while receiving approval from this group of population [Justice Centre Hong Kong -@VoicesProtectionGo2014 ; Vision First -@RefugeeCommunitySupports2015 ; Refugee Union -@OCTOBERROUNDUPREFUGEE2018] . Indeed, legislator Cheung's prominent advocacy for the rights of asylum seekers had indirectly caused him to become a victim of political smearing a few months before the 2016 Legislative Council election, as political banners imposting legislator Cheung's party were seen hanging in streets which maliciously called the legislator "the father of refugees" [@ngoPoliticalDarkArts2016] . It should also be noted that, nevertheless, a more lenient attitude towards asylum seekers does not mean that the pro-democracy camp totally disregards the perceived issue of bogus refugees. Even though legislator Charles Mok condemned Holden Chow's motion against "bogus" refugees was "disturbing", he also attributed the most responsibility of "bogus non-refoulement claims" to the Government due to the latter's inefficiency and lack of knowledge in handling the issue [@chengLegislatureRejectsLawmaker2016] . But in general, the pro-democracy camp supports a more humane treatment towards non-refoulement claimants who are genuinely in need of fleeing from their countries due to prosecution.

Lastly, the localist camp's stance on dealing with asylum seekers is less confrontational than that towards mainland Chinese. As one of the few localist lawmakers who were not disqualified in the oath-taking controversy by December 2016, Dr Cheng Chung-tai's speech on Holden Chow's anti-fake-refugees motion had two points which worth highlighting[^2] [@Hui4yi4Guo4cheng2Zheng4shi42016] (p.1232-33). Firstly, he shared the pro-democracy camp's view of the main reason for the so-called "bogus refugees" issue being the Government not allocating adequate resources to assess the claimants' applications. But the more intriguing point of view is how he framed Hong Kong's signatory status of the UNCAT as a proof of the city having its own *de-facto* sovereignty from mainland China, and thus he opposed CY Leung's suggestion of withdrawing from the treaty since it would signify Hong Kong's regression in civlisation to the world. Interestingly, the localist camp's reservation of adopting more stringent measures against asylum seekers has drawn smear from some pro-Beijing medias, such as an editorial from @thesunJiu4shi4lun4shi4Ben3tu3pai4Shi1sheng12016 accused the localists of "remaining silent" on non-refoulement claimants wasting public resources of Hong Kong.

[^2]: Of course, one could argue that Dr Cheng's speech might not necessarily represent the view on asylum seekers by the *whole* localist camp, given localism is more of an umbrella term encompassing rather heterogeneous political organisations as mentioned before. Nevertheless, his stance on asylum seekers could at least be interpreted as one of the possible ways that localists may view the issue.
