---
title: Methods
author: Chin Man KWAN
chapter: 3
in_context: True
knit: iheiddown::chapter_pdf
output: iheiddown::chapter_pdf
---

\setcounter{chapter}{2}

# Methods {#methods}

In the previous chapter, I covered the literature on how perceptions of national identity may affect the attitudes towards immigrants, how political camps in Hong Kong define national identity and their attitude towards the treatment of non-refoulement claimants. With the above theoretical basis of how each political camp is likely to perceive the issue of asylum seekers in Hong Kong, I will now move on to investigate how informative the political affiliation of media outlets is for predicting the sentiments of news articles on non-refoulement claimants after accounting for other factors, such as the content and the metadata of the news articles. This chapter will discuss the research strategies in detail before presenting the analysis results in the next chapter.

## Hypothesis

Following the aforementioned discussion, the pro-Beijing camp expresses more overt hostility towards non-refoulement claimants in Hong Kong than other political camps by frequently referring to the latter as "fake refugees" which warrant solutions derived by the HKSAR Government in order to protect the interests of the Hong Kong society. Therefore, I decided to formulate H~1~ as follows:

> H~1~: Pro-Beijing media outlets are more likely to negatively portray asylum seekers than media outlets from other political camps.

Should the analysis result demonstrates that the probability of a news article being negative (how the sentiments are operationalised will be discussed later) is higher if it is published by pro-Beijing media outlets, then this hypothesis should be accepted.

## Data collection

The data will be drawn from Chinese language news media reports on asylum seekers in Hong Kong published by local printed newspaper outlets during 2019[^1]. For the retrieval of the relevant newspaper articles, I will rely on the *WiseNews* database which can fetch news articles with search keywords[^2]. While it would have been more ideal to also include online news media into the dataset as @leeChangingPoliticalEconomy2018 mentions that they have become quite prominent in the 2010s for providing counter-narratives to the mainstream media which are often co-opted by the Chinese Government[^3], WiseNews does not directly provide the texts of online media news article and thus requires additional steps of web scrapping which are, unfortunately, beyond the author's capacity by the time of writing. That being said, including only the printed news media during 2019 would still cover 16 of the well-known news media which were included in the 2019 media credibility survey by @cuhkPublicEvaluationMedia2020. In other words, just searching for printed news media outlets still allows me to discover whether the attitudes of reporting on asylum seekers by some of the most well-known and widely circulated media outlets in Hong Kong might be related to their political associations.

[^1]: The full list of the included newspaper outlets is provided in *table 3.2*.

[^2]: I would like to thank my friend in Hong Kong helping me gain access to the database, which would otherwise have been extremely difficult.

[^3]: It should be noted, however, that by the very beginning of 2022, several online media outlets such as *Stand News* has dissolved after the flagship pro-Democracy newspaper outlet *Apple Daily* was forced to shut down in June 2021. The implication of this phenomenon to the media's narrative on asylum seekers in Hong Kong will be discussed further in the conclusion chapter.

The reason for choosing to collect media reports published in 2019 is because it was the year when the Anti-Extradition Law Amendment protest first broke out in June and then lasted for several months, a period when one can argue the manifestation of political ideologies and identities should be the most salient for all the political camps. This should indeed be the case for both the pro-democracy camp whose supporters participated in several large-scale protests and sometimes even engaged in numerous violent clashes with the Hong Kong police to oppose a law that would have permitted extradition of fugitives to mainland China, and the pro-Beijing camp whose authority was once again immensely challenged after the 2014 Umbrella Movement. Accordingly, it would be interesting to investigate whether the issue of asylum seekers still remained its salience and was reported in similar manners given the co-occurrence of another arguably more salient political event (i.e. the anti-Extradition Law protests), as compared to when the issue first had become prominent back in 2016. Specifically, analysing newspaper articles in 2019 provides an opportunity to observe whether and how asylum seekers in Hong Kong might be represented by the media in tandem with major political events.

It is worth discussing some limitations of using media reports as the source of data. For starters, media reports do not necessarily reflect how individuals identifying with each political camp might perceive asylum seekers directly and might not be fit for investigating the causal mechanism of how definition of Hong Kong's national identity may cause a political camp to frame asylum seekers in particular ways in face of the public. Despite these shortcomings, media reports can still adequately help test the hypothesis of whether narratives on asylum seekers in Hong Kong may vary by political camps which share drastically different definitions of Hong Kong's national identity because media reports will likely reflect each political camp's preferred version of framing on the issue to which they would like to propagate. In fact, previous research about the framing of asylum seekers by mass media [@cooperMediaCoverageRefugees2017; @mckayAnyOneThese2011; @ngFramingIssueAsylum2019; @odohertyAsylumSeekersBoat2007] point to its potential impact on affecting how the public may perceive the issue via being a major provider of related information, and sometimes media reports may even serve to justify policy-making decisions or reflect the government's position on the issue (when the media simply repeat the information provided by officials). Drawing from @fongInbetweenLiberalAuthoritarianism2017 and @leeChangingPoliticalEconomy2018, the media industry in Hong Kong is quite remarkable for their political stances, and numerous outlets have their owners being affiliated with the Chinese and/or HKSAR Governments. Therefore, reports published by Hong Kong media outlets should be able to reflect political camps' attitudes towards asylum seekers and, perhaps more importantly, the version of framing that they would like to persuade their readers to accept, thereby making them a suitable data source to gauge how may each political camp's discourse on asylum seekers vary given their contrasting definitions of the city's national identity.

Language-wise, including only Chinese-language news media omits how asylum seekers may be represented by English-language media in Hong Kong (e.g. the South China Morning Post) and thus cannot investigate whether the representation of asylum seekers by English-language media outlets to potential non-Chinese audience may also vary based on each outlet's political affiliation. Moreover, solely focusing on textual content of the media reports means discarding graphical and (if also published online) audio-visual materials accompanied in a given news report, which may contain additional information that are not observed in the texts of news articles. Nevertheless, analysing the textual content of the media reports should still yield a considerable amount of information about the representation of asylum seekers in Hong Kong by media outlets linked to different political camps, since after all a large proportion of the content in news reports are represented textually.

To search for relevant media reports on WiseNews, I will refer to the keywords used by @ngFramingIssueAsylum2019 which are commonly used for referring to non-refoulement claimants by the media. These terms can either be directly describing this group of population (e.g. refugees, illegal immigrants) or policies related to asylum seeking (e.g. non-refoulement claim, immigration paper). Table 3.1 lists all the Chinese terms used for searching the relevant news articles on WiseNews and their meanings in English. Additional notes are used for indicating whether some articles were omitted and why. The author also omitted articles only mentioning the keywords briefly throughout the main text which discusses issues not directly related to asylum seekers. As for the keywords "South Asian", "illegal immigration" and "human snake", the author only included news entries fetched from these keywords if at least one of the other keywords directly referring to asylum seekers (i.e. non-refoulement claim(ant), torture claim(ant), asylum seeking, refugee and immigration paper) co-appeared in either the title or main text. This is to ensure that the news articles in the dataset are obviously describing non-refoulement claimants in Hong Kong.

| Original terms in Chinese pinyin | Literal meaning in English                                     | Notes                                                                                    |
|----------------------------------|----------------------------------------------------------------|------------------------------------------------------------------------------------------|
| mian3 qian3fan3 sheng1qing3      | Non-refoulement claim(ant)                                     |                                                                                          |
| ku4xing2 sheng1qing3             | Torture claim(ant)                                             |                                                                                          |
| fei1fa3 ru4jing4, ren2she2       | Illegal immigration, human snake (alias of illegal immigrants) | Excluded illegal immigration from mainland China                                         |
| xun2qiu2 bi4hu4                  | Asylum seeking                                                 | Excluded asylum seekers *outside of* Hong Kong                                           |
| nan4min2                         | Refugee                                                        | Excluded refugees *outside of* Hong Kong and Hong Kong activists seeking refuge overseas |
| nan2ya4                          | South Asian                                                    | Articles about the South Asian region are excluded.                                      |
| xing2 jie1 zhi3                  | Immigration paper                                              | Documents issued by the Immigration Department to non-refoulement claimants.             |

: Translation of the keywords used to search for media reports on WiseNews

## Machine learning analysis

### Model selection

While the dataset can certainly be analysed via human coding to qualitatively investigate in how the usage of language in reporting on non-refoulement claimants may vary by political camp, due to my motivation of testing the efficacy of machine-learning-based sentiment analysis on non-Chinese-language as well as concern on time and resource intensiveness of manually coding over 500 articles in the dataset, I will instead use supervised machine learning models to test H~1~. In other words, H~1~ will be treated as a sentiment analysis problem which classifies the *polarity* of the news articles (i.e. whether they reported on asylum seekers *positively, neutrally or negatively*). How the independent (both the media outlet's political camp and other controls) and dependent variables are operationalised and coded will be discussed in the next section, and for now I will talk about what kinds of tools and models will be used for the analysis. Nevertheless, it is important to remind that even if machine learning methods can potentially improve the scalability of sentiment analysis on larger datasets, there are also caveats listed by @vanatteveldtValiditySentimentAnalysis2021 such as accidentally identifying spurious relationships between variables or overfitting which can hamper the validity of the analysis. Thus, it is important that I keep these issues in mind while modelling the data and adopt remedies to these problems if necessary.

Starting with the models that will be used for the analysis, I will rely on some commonly used classification models. Candidate models thus include logistic regression, support vector machine (SVM), random forest and gradient boosting. Although @vanatteveldtValiditySentimentAnalysis2021 also mention that deep learning is another popular choice of machine learning model for sentiment analysis tasks, I did not use it due to the relatively small size of the dataset at hand as well as the difficulty of interpreting the features' impact on the dependent variable directly from deep learning models. I will first run some baseline models with the default parameter settings of the models before selecting one for hyper-parameter tuning based on their performance on their *f1 scores* (which measures the harmonic mean of *precision* and *recall*) on both the test data set (which will be 20% of observations in the original dataset stratified by the dependent variable) and 5-fold cross validation[^4]. Compared to metrics like accuracy and the ROC-AUC score, using f1 score as the evaluation metric can better measure a model's performance if there is class imbalance in the dependent variable.

[^4]: Just a reminder, the formula of calculating a model's F1 score is: $2\cdot\frac{\left(precision\cdot recall\right)}{\left(precision+recall\right)}$ [@pedregosaScikitlearnMachineLearning2011].

The reason for relying on the f1 score generated from both the testing set and 5-fold cross validation for model selection is because of the inherently small size of the dataset. In the case of having small datasets, using only the test data for model evaluation may risk over- or under-estimating the performance of the model due to the small number of observations only available in the testing data [@brownleeTrainTestSplitEvaluating2020]. On the other hand, only using 5-fold cross validation on the whole dataset for training the model cannot have any indication about how the model may perform on predicting data which are completely unseen beforehand to test for its ability to generalisation. Consequently, I decided to take into account of each model's f1 score in both scenarios for a more comprehensive assessment of their performance. The model which overall performs the best will then be used for calculating the *SHAP values* of the features which evaluate how much impact each feature has on the model prediction when the features is at certain values versus at its baseline value [@lundbergUnifiedApproachInterpreting2017]. In essence, the higher the magnitude of a feature's SHAP value, the larger its impact of the model's prediction. And for classification models, positive SHAP value means that an observation is *more* likely to be predicted for belonging to a certain class in the dependent variable, whereas negative SHAP values mean an observation is *less* likely to be predicted for belonging to a certain class.

### Data pre-processing

To pre-process the articles into suitable formats as machine learning model inputs, I will also transform the news articles into a term-document matrix which records the frequency of each word (i.e. token) appearing in each article (i.e. document). Instead of simply counting the frequency of each token in the document corpus, I will use the term-frequency inverse-document-frequency (TF-IDF) matrix transformation which also scales down the importance of tokens that appear in a large proportion of the documents in the corpus since these tokens are likely to be less informative on the content of the documents than tokens that appear in smaller proportions of the documents [@pedregosaScikitlearnMachineLearning2011]. Note that only tokens which appears in all least 2% of the documents in the corpus will be included in the term-document matrix so that I do not include too much noise in the resulting TF-IDF matrix.

Due to the relatively small size of the dataset (with only around 550 articles), I will also adopt non-negative matrix factorisation (NMF) to reduce the dimensionality of the dataset to prevent overfitting. According to @stevensExploringTopicCoherence2012 (p.953), the matrix denoted as *H* which captures the weight of each topic (as columns) in each document (as rows) of the corpus can help summarise the information of the articles in terms of which topic(s) they primarily focus on. Thus, I will use NMF to transform the TF-IDF matrix into another which summarises the news articles into a certain number of pre-defined latent topics (the exact number will be figured out at the ***preprocessing*** section in next chapter), and then use this matrix as part of the inputs for the models.

There are also some model-specific pre-processing steps (e.g. standardising numerical features so that their means are centred at 0 and are on the same scale) which will need to be performed accordingly. I will detail them out as necessary at the **Sentiment analysis** section in next chapter.

### Implementation

The majority of the implementation from data pre-processing, modelling to validation will be done via the `scikit-learn` package in Python [@pedregosaScikitlearnMachineLearning2011], whereas the tokenisation of the Chinese-language news articles will be done by the `jieba` package which is designed for natural language processing in Chinese [@junyiJieba2021]. For better tokenisation of the articles, I will also remove stop words, punctuations and hyper-links of the texts and add words related to Hong Kong politics (downloaded from @elgarteoHKPolDictHongKong2021) and asylum seekers into the dictionary. As for the gradient boosting model, the `XGBoost` package [@chenXgboostExtremeGradient2015] will be used since it is one of the most renowned machine learning models in data science, and it also offers a lot of options for tuning the model for better performance.

## Operationalisation

### Main independent variable (a.k.a main feature)

Starting from the main independent variable which classifies the associated political camp of the media outlets, I will mainly refer to the literature exploring how Hong Kong's media industry is intertwined with politics and perform additional research when needed. I consulted the articles by @fongInbetweenLiberalAuthoritarianism2017 and @leeChangingPoliticalEconomy2018 on the development of post-1997 Hong Kong's media industry, of which they have documented the co-optation of Hong Kong media outlets by the Chinese Government (e.g. the major shareholders holding positions in such as Chinese People's Political Consultative Conference). Building on the concept of "allocative control" (p.11) by @leeChangingPoliticalEconomy2018 about media outlet owners having the ultimate decision on the personnel and resources at the newsroom's disposal for reporting news which may lead to self-censorship of the frontline journalists, I will code media outlets whose owners are affiliated with the official Chinese and/or Hong Kong Government organisations as belonging to the pro-Beijing camp. As for those media owners with less apparent links with the Chinese or Hong Kong Governments, I will decide the classification according to whether the owners are known to be affiliated with a certain political camp and how a given media outlet is perceived for its political stance. Media outlets without apparent political stances are labelled as "neutral". Table 3.2 is the resulting classification scheme. ***Note that due to the medium of publication of localist news media being overwhelmingly online, none of the outlets in that camp was included in the dataset. Therefore, it would not be possible to test whether the sentiment of reportage on non-refoulement claimants in Hong Kong may be related to localist camp affiliation of media outlets.***

| Associated political camp                                                                                          | Media outlets                                                                                                                                        |
|--------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------|
| Pro-Beijing camp (directly owned by the Liaison Office of the Central People's Government or the HKSAR Government) | Wen Wei Po, Hong Kong Government News, Hong Kong Commercial Daily, Ta Kung Pao                                                                       |
| Pro-Beijing Camp (owners affiliated with political institutions on mainland China/ HKSAR Government)               | Oriental Daily News, Sing Tao Daily, Sing Pao, Headline Daily, Hong Kong Economic Journal, Hong Kong Economic Times, am730, Sky Post, HK01 Newspaper |
| Pro-Democracy camp                                                                                                 | Apple Daily, Kung Kao Po[^5]                                                                                                                         |
| Localist camp                                                                                                      | N/A                                                                                                                                                  |
| Neutral                                                                                                            | Metro Daily, Ming Pao Daily News                                                                                                                     |

: Classification of the associated political camp of media outlets in Hong Kong included into the sample, source: @fongInbetweenLiberalAuthoritarianism2017; @leeChangingPoliticalEconomy2018; author's own research

[^5]: The decision to put *Kung Kao Po* under the pro-democracy category is made after using the keyword *anti-extradition* (*fan3xiu1li4*) in Chinese to search for relevant news articles on the newspaper's [website](https://kkp.org.hk/view-search), which yielded entries that are overall sympathetic to the protesters and disapprove the HKSAR Government's handling of the protest.

#### Publication of news articles by outlet and political camp

Figure 3.1 shows the number of news articles on non-refoulement claimants published in 2019 by newspaper outlet (left) and political camp (right). Consistent with the study by @ngFramingIssueAsylum2019, Oriental Daily News continues to be the media outlet covering the most frequently on asylum seekers with 384 (or `r round(384/557 * 100, 2)`%) articles throughout 2019. By contrast, the second-most frequent publisher *Sing Tao Daily* only had 45 entries (or `r round(45/557 * 100, 2)`%) of the total number of articles published. Each of the other newspaper outlets only constituted to a small portion of news articles about non-refoulement claimants in 2019. Therefore, the issue of asylum seekers in Hong Kong still appeared to be the most salient for Oriental Daily News by 2019, evidenced by its unmatched volume of articles related to this topic vis-a-vis other media outlets.

If we look up the number of news articles on non-refoulement claimants by political camps, the pro-Beijing camp dominated the coverage of asylum seekers in Hong Kong in 2019 largely due to the huge volume of publication by Oriental Daily News. Meanwhile, both neutral and pro-democracy newspaper outlets published similar amounts of articles throughout 2019, and both camps constituted to small proportions of the share of articles during the year. Even if we omitted the sheer volume of articles published by Oriental Daily News, the pro-Beijing media would still have `r 557-384` articles published altogether which was still considerably more than the quantity of articles written by neutral and pro-democracy media outlets combined. A question that may arise is that given the comparatively much smaller volume of publication on non-refoulement claimants by neutral and pro-democracy newspaper outlets, is it likely that the articles published by outlets from these two camps will still have potential influence in shaping the narrative on asylum seekers in the broader society? The answer to this question is a rather assuring yes for these two groups of outlets.

```{python, fig.cap="News articles on asylum seekers in 2019 by news outlet (left) and political camp (right)"}
# Setting up packages
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
polit_camp_df = pd.read_csv("data/asylum_seekers_articles_final.csv")

fig, axes = plt.subplots(1,2)

# Plotting by-outlet amount of articles
articles_outlet = polit_camp_df.value_counts('Newspaper')
sns.barplot(x=articles_outlet, y=articles_outlet.index, ax=axes[0])
axes[0].set(xlabel='Number of articles (in base-10 log scale)', ylabel='', title='By newspaper', xscale="log")
for idx, value in enumerate(articles_outlet):
    axes[0].text(value + 5, idx + 0.2, value)

# Plotting by-camp amount of articles
sns.countplot(x='Political_camp', data=polit_camp_df, ax=axes[1])    
axes[1].set(xlabel='', ylabel='Number of articles', title='By political camp')
count_by_political_camp = polit_camp_df['Political_camp'].value_counts(sort=False)
for idx, value in enumerate(count_by_political_camp):
  axes[1].text(idx - 0.1, value + 5, value)
axes[1].set_xticklabels(['Pro-Beijing', 'Neutral', 'Pro-democracy'], rotation=60)
plt.tight_layout()
plt.show()
plt.clf()
```

Starting with outlets in the pro-democracy camp, *Apple Daily* is one of the most popular paid newspapers in Hong Kong since it occupied over half (54.7%) of the market share in the paid newspaper market and was ranked as the second most popular printed newspaper in Hong Kong by 2019 [@adintimeMostWidelyreadMagazine2021]. Apart from being widely circulated in society, Apple Daily was also known for its pronounced pro-democracy stance, and it gradually transformed from a pure sensationalist tabloid to flagship newspaper which framed and reported news that were critical to the Beijing and HKSAR Governments since the early 2000s which contributed to its growing popularity, and the forced closure of this outlet was also reported as one of the greatest shocks towards the city's freedom of press by foreign media outlets like the BBC [@tanAppleDailyHong2021]. As for *Kung Kao Po*, it is a weekly published newspaper founded in 1928 for the Catholic Hong Kong Diocese which often organised religious events to commemorate pro-democracy protests such as the Umbrella Movement [@kungkaopoChen2Shu1ji1Yu32019], and given Hong Kong has around 12% of its population identifying as Christians with some of the believers being quite vocal and prominent in pro-democracy activism [@hitchensOpinionChristianHeart2021], the reportage of this newspaper on asylum seekers in Hong Kong can thus be treated as representing the narrative on this issue via the perspective of pro-democracy Christians. Therefore, even if these two pro-democracy outlets published much fewer articles than the pro-Beijing camp outlets on non-refoulement claimants, they may still carry influence over the public's perception towards asylum seekers within the city via framing this issue due to their considerable reader bases.

As for the neutral outlets, it is necessary to include their articles on non-refoulement claimants into the dataset because they also occupy an important role in Hong Kong's media industry by providing objective media coverage which avoids explicit political allegiance with a particular camp. Despite the controversial change of chief editorship in 2014, @leeChangingPoliticalEconomy2018 argues that Ming Pao has established itself as one of the "widely circulated, influential and credible" (p.12) outlets in Hong Kong since the 1980s, and its owner *Tiong Hiew King* has rather emphasised that Ming Pao report news objectively similar to the Chinese newspapers under his ownership in Malaysia. Likewise, being the first free printed newspaper available in Hong Kong from 2002 to 2019 (which then became an online newspaper since 2020) as the localised edition of *Metro International*, including Metro Daily as one of the outlets covered in the dataset can also help investigate whether and how local editions of international media may pay attention to the issue of asylum seekers in Hong Kong (as it turned out Metro Daily hardly covered this issue during its last year of publication as a printed newspaper).

In short, even if the number of articles on non-refoulement claimants published by the neutral and pro-democracy outlets included in the dataset was small, their reportage should still be able to reach out to a considerable amount of audience to potentially influence the latter's perception towards asylum seekers because of the outlets' wide circulation as well as their status as some of the leading media outlets in their respective political stance.

### Dependent variable (a.k.a target variable)

As mentioned before, the dependent variable of H~1~ will be the sentiment of the news articles towards asylum seekers in the polarities of *positive*, *neutral* and *negative*. But how exactly should these three polarities mean in this context? Again referring to the literature can help devise a sound coding scheme. Drawing @mckayAnyOneThese2011, @cooperMediaCoverageRefugees2017 and @ngFramingIssueAsylum2019, *positive* articles usually acclaim the person or event in concern, describe personal stories, report expert opinions without derogatory terms or depict refugees favourably, *neutral* articles simply report an incident without an overt sentiment or opinion towards particular stakeholders and with little interpretation by the journalists, and *negative* articles frame asylum seekers either as bringing problems to the host society or use inaccurate terms to delegitimise this group of population. I will follow these coding criteria for the polarities of the news articles in the dataset since these definitions suit the purpose of this study. The numerical representation of the polarities in the dataset will be as follows, namely, positive articles will be coded as `2`, neutral articles will be coded as `1`, and negative articles will be coded as `0`.

For the context of Hong Kong about the "incorrect" terms and information used for describing asylum seekers, I will refer to expert opinions about whether descriptions of asylum seekers in Hong Kong are founded[^6]. For example, @ngFramingIssueAsylum2019 point out that the term "fake/bogus refugees" (*jia3 nan4min2)* should be considered as both derogatory and inaccurate because those applying for non-refoulement claims are not automatically qualified as refugees while awaiting the final decisions of their applications. *Therefore, the polarity of news articles in which the news media directly refers non-refoulement claimants as "fake refugees" in its reportage will be coded as negative, but the report should be coded at least as neutral instead if the news outlet is merely quoting someone who describes non-refoulement claimants as "fake refugees".* Furthermore, @ngCriminalizingInnocentsSocial2020 mentions that non-refoulement claimants are forced to be illegal immigrants by the policy design of the HKSAR Government so that this group of population can be excluded from social rights that legal residents enjoy. News articles equating non-refoulement claimants as illegal immigrants will thus also be coded as negative since such reportage is justifying the exclusion of non-refoulement claimants by resorting to their illegality that had been forced upon by the HKSAR Government.

[^6]: A detailed discussion of the depiction of asylum seekers in Hong Kong can be found in @ngCriminalizingInnocentsSocial2020 and @ngFramingIssueAsylum2019.

### Control variables (a.k.a features)

I will also incorporate some control variables to see if the association between political camps and polarities of the news articles still remains significant afterwards. For starters, the time when the articles were published will be included as a control, though I will bin the twelve months into four evenly split quarters (`Quarter`) to avoid this category from having too high cardinality which may hamper the performance of tree-based models[^7], with `Q1` covering from January to March, `Q2` covering from April to June, `Q3` covering from July to September, and `Q4` covering from October to December. As 2019 was also the year when one of the most large-scale and long-lasting pro-democracy protests broke out, it would be interesting to see if the polarities of the news articles might vary according to in which Quarter it was published, and one could argue that the anti-extradition law witnessed some of the most intense conflicts during `Q3` and `Q4`.

[^7]: A detailed discussion of the potential problems posed by highly cardinal categorical features on tree-based models can be found in @lerHighNumberUnique2021, but the main issue is that the higher the cardinality of a categorical variable, the more splits will be needed by tree-based models which may then considerably increase the computational costs of the models.

Moreover, the presence of racial labels in the news articles will be included as a control since it is possible that more overtly racialised discourse may be associated with more negative sentiments towards asylum seekers in general according to the literature. This variable will be named `Racial_label` in the dataset and will be binary, with `1` meaning there is presence of racial labels in the main text and `0` otherwise. Racial labels referring to both regional (e.g. South Asia, Africa) and national (e.g. the nationalities included in figure 2.2) will be counted. Lastly, the metadata of the news articles, namely the character counts of titles and main texts, will also be added to see if the lengths of the articles may be associated with their sentiment towards asylum seekers.
