---
title: Conclusion
author: Chin Man KWAN
chapter: 5
in_context: True
knit: iheiddown::chapter_pdf
output: iheiddown::chapter_pdf
---

\setcounter{chapter}{4}

# Conclusion {#conclusion}

To recap, I used XGBoost to build a multi-class classification model to investigate whether the sentiments (in the polarities of *negative, neutral and positive)* of the printed newspaper articles about non-refoulement claimants in Hong Kong may vary according to a newspaper's affiliated political camp in 2019, a year when the city witnessed one of the most large-scale and long-lasting pro-democracy protests since 1997. The SHAP values calculated from the tuned XGBoost model (which obtained a f1 score of 0.7616 in 5-fold cross validation and 0.8814 in the testing set) demonstrate that compared to outlets with other political affiliations, pro-Beijing newspaper outlets are generally *more* likely to publish negative articles containing derogatory or incorrect descriptions about non-refoulement claimants while also being *less* likely to publish positive articles which report on asylum seekers sympathetically and favourably, thereby providing empirical evidence to support H~1~. On the contrary, although the magnitudes in SHAP values are smaller, pro-democracy newspaper outlets are predicted to be *less* likely to publish negative articles and more likely to write positive articles on asylum seekers, whereas neutral outlets are at least less likely to cover non-refoulement claimants in negative light. Some of the topics covered in the news articles are also informative in predicting the sentiments and point to rather clear directions of how a higher presence of a given topic may affect the sentiment of a news article, except for the `Problem and solution` topic which by definition has a much wider scope of how it can be mentioned by journalists than other topics discovered by NMF.

The above results suggest that definitions of national identity by political camps may indeed be correlated to their attitudes of how asylum seekers should be treated in society. Specifically, political camp which highlights more on the ethnic dimension of national identity is likely to be associated with more negative attitudes towards asylum seekers, whereas political camp which puts more focus on the civic values in defining the national identity will be more likely to be sympathetic towards asylum seekers. In this sense, how national identity is defined may then serve to be a salient factor in affecting how individuals perceive whether their society should be more lenient or stringent towards asylum seekers and how likely individuals may connote this group of vulnerable population. Obviously, the theoretical observations made from the case of Hong Kong should be formally tested in other contexts to see to what extent they are applicable, but the fact that the correlation between definitions of national identity (as reflected by different political camps) and attitudes towards asylum seekers is found in Hong Kong means that the potential influence of this correlation should not be overlooked, especially for studies regarding the attitudes towards asylum seekers in regions where the reach of the central government's political authority is contested.

Moreover, as shown by the performance on the f1 score of the tuned XGBoost model, using machine-learning-based approaches to analyse the sentiments of Chinese-language text can be a viable alternative to analysis done by human coding. This will be quite useful when the document corpora contain a huge volume of text data that will be too resource-intensive to be analysed manually. For instance, the meeting minutes in the Legislative Council which records speeches by legislators about their opinions on bills can be analysed via automated approaches to discover whether the policy positions of different political parties on a given issue could be more segregated based on the pro-Beijing vs pro-Democracy line or the socio-economic left-right dimension until the opposition was effectively barred from political participation in 2020. More possibilities of social sciences research regarding the politics of Hong Kong can be opened up by incorporating techniques from machine learning in general and natural language processing in particular.

## Limitations

Even though the XGBoost model produced results with satisfactory performance, this thesis still suffers a few limitations apart from those mentioned in the *methods* chapter. The most obvious one will be the relatively small size of the dataset. Particularly, observations belonging to the positive polarity class were very rare which inevitably increased the variance of the predictions on this class. There are two potential ways which could have alleviated this limitation. For starters, the dataset could extend the covered period to include news articles on non-refoulement claimants from the years 2017 and 2018. A further step can be taken to also include articles from 2016 which can then test if the sentiments of the news articles on asylum seekers in Hong Kong might also be correlated to if a given year had elections that the public could vote. Besides extending the temporal coverage of the dataset, news articles by online news media can also be included via web scrapping. Indeed, this may provide a solution to the lack of sufficient observations of positive articles encountered in the dataset of this thesis, as @ngResistanceFramingPortrayal2021 argue that articles on non-refoulement claimants by online news media from mid-2015 to mid-2016 generally focused more on the humanitarian issues than criminal activities linked to asylum seekers vis-a-vis printed newspapers in the same period. Given that localist news media outlets publish almost exclusively online, incorporating online news articles will also provide an opportunity to see if localist affiliation of media outlets may be correlated to the sentiments of news articles on non-refoulement claimants.

Partly related to the small size of the dataset, more sophisticated models could have been used if there had been more observations. As much as TF-IDF and NMF altogether discovered latent topics in the current dataset that are largely semantically coherent, the deep-learning-based method of *word embeddings* could also be applied on the news articles if more observations were available. Besides reducing the dimensionality of the dataset, another added benefit of word embeddings over simple bag-of-words approaches is that the resulting embedding vector can capture the relationships between words since similar words will share similar encodings after the model's weight are trained with sufficient data [@tensorflowWordEmbeddingsText]. Indeed, the ability of word embeddings to capture the relationships between word tokens can help further understand how media outlets from different political camps may use particular terms to depict asylum seekers even in the case of having large datasets where human coding will prove to be difficult.

## Future research directions

While performing sentiment analysis on the news articles about non-refoulement claimants is one way to study how narrative on this group of population in the mass media may vary by political camps, there are certainly other possibilities to engage with this topic. One of the potential research directions will be using *unsupervised* machine learning techniques such as cluster analysis to see how (dis)similar media outlets from different political camps are in reporting on asylum seekers in Hong Kong both *between* and *within* political camps. Essentially, cluster analysis on the news articles can be done by first reducing the dimensionality of the term-document matrix via techniques like NMF (used in this thesis) or word embeddings (should there be enough data) before using clustering algorithms (of which *K-means* is a popular one which assigns each data point into a pre-defined number of clusters `k` according to the euclidean distance between each data point and the centroid of each cluster).

For the cluster analysis of reportage on the level of *between* political camps, it may be worth investigating whether neutral newspaper outlets cover non-refoulement claimants more similarly to pro-democracy or pro-Beijing outlets. As for the level of *within* camp cluster analysis, it will also be interesting to see if some media outlets within a political camp differ their reportage from their peers despite having the same political affiliation.

## How may the promulgation of the National Security Law affect the public discourse on asylum seekers in Hong Kong?

With the finding that pro-Beijing newspaper outlets are more likely to negatively depict asylum seekers in Hong Kong, the suppression of the opposition camp by the HKSAR Government in both official institutions and the mass media can have profound implications of how non-refoulement claimants may be treated in the future. In short, as the pro-democracy camp has been crippled for being able to influence the public discourse on socio-political issues in Hong Kong by mid-2020 following the promulgation of the National Security Law which tightens political control by the HKSAR Government, it is likely that the narrative on asylum seekers in Hong Kong will be dominated by the pro-Beijing camp in the mass media which, coupled with the Government's increasingly stringent measures against non-refoulement claimants, will likely create more and more hostility against non-refoulement claimants in society.

Starting with the official institutions like the legislature, preliminary evidence suggests that the HKSAR Government is already exploiting the lack of opposition to push forward more stringent measures in cutting the number of non-refoulement claims no matter if they are genuine or not. Just two months after the announcement of pro-democracy legislators of their resignations [@cheungAllHongKong2020], the Security Bureau proposed a bill in January 2021 for adding another detention centre of non-refoulement claimants who are alleged to commit crimes and, without clear definition, pose "security risks", and the more concerning rhetoric from the speech by the head of the Bureau is that he claimed "non-refoulement claims poses a lot of troubles to society" without even differentiating if he was just referring to the "bogus" claims or not besides bashing non-refoulement claimants for being illegal immigrants and costing Hong Kong's public money for the assessment of their claims [Security Bureau -@AmendingLawsReinforce2021]. With virtually no presence of oppositions in the legislature, this bill was overwhelming passed in April by pro-Beijing legislators [Oriental Daily News -@orientaldailynewsChrisTangPingkeung2021]. As the recent 2021 Legislative Council election was concluded after an overhaul of the electoral system which essentially permits candidacy only to the "patriots" loyal to the Beijing and HKSAR Governments [@lauPatriotsOnlyHong2021], the door for the oppositions to advocate alternative political discourses in the legislative has been shut, meaning that the Government will be quite unlikely to face even just verbal oppositions while proposing bills to be passed in the future, including those which further exclude non-refoulement claimants who are already deprived of a substantial amount of societal rights as mentioned by @ngCriminalizingInnocentsSocial2020.

While the mass media in Hong Kong used to be where alternative narratives on socio-political issues contrary to the official rhetoric could be found in alternative media as @leeChangingPoliticalEconomy2018 mentioned, by early 2022 this may not be the case anymore as some pro-democracy media outlets have already been forced to defunct due to increasing political pressure and legal risks. The first outlet forced to shut down was the flagship pro-democracy newspaper *Apple Daily* in June 2021 after the HKSAR Government had frozen its assets under the pretext of the outlet's violation of the National Security Law [@tanAppleDailyHong2021]. Just as 2021 ended, the popular pro-democracy online media *Stand News* shut down as well after the Hong Kong police raided its office and arrested senior staff [@ngHongKongProdemocracy2021], followed by the closure of another online pro-democracy news outlets named *Citizen News* days after [BBC -@HongKongProdemocracy2022]. It is probable that more non-pro-Beijing media outlets will be forced to shut down in the future as the HKSAR Government continues its crackdown on political dissidence, thereby causing the pro-Beijing camp to be able to completely dominate how public discourse will be formulated in the mass media. Consequently, the media's representation of the non-refoulement claimants in Hong Kong will likely be almost unanimously negative without any counter-narrative by alternative media which used to be read by a considerable amount of audience. As the study by @boomgaardenHowNewsContent2009 show, more pejorative coverage of refugees by the media may cause the public to be more averse towards this group of vulnerable population in later periods, and the effect of negative news coverage may become even more salient when the levels of immigration and asylum seeking applications are perceived to be high. Coupled with mass media's potential to influence how the public may think about the issue of asylum seekers in Hong Kong, the domination of negative stories which constantly portray non-refoulement claimants as criminals or threats to public security will be anything but conducive to more humane treatments and tolerance towards this group of vulnerable population.

As the Government and pro-Beijing media outlets work in consort to push forward the framing of non-refouelment claimants as social problems which should not be welcomed in society and demand stringent measures to be solved efficiently amid the lack of alternative discourse or even actions (such as former legislator Dr. Fernando Cheung's advocacy for the human rights of asylum seekers) from the oppositions, it can be expected that Hong Kong will gradually become a city that is more and more unfavourable towards individuals who are forced to flee from their home countries due to threats of tortures. Worse, *CY Leung's* suggestion of quitting the UNCAT may even become true in the future, thereby further deteriorating the human rights situation in Hong Kong which has already been concerned globally as the Government cracks down the oppositions [United Nations -@HongKongHuman2021].
