---
####################
## Metadata       ##
####################
doctitle: |
  How may the contestation of the definition of national identity by different political camps relate to their attitudes towards asylum seekers? Using XGBoost to analyse the newspaper articles in Hong Kong
firstnames: Chin Man
lastnames: Kwan
# thesisno: 12345
phd: false # Or: false for Masters
department: The International Relations/Political Science Department
degreedate: January 2022
supervisor: Prof. Sungmin Rho
secondreader: Prof. Ravinder Bhavnani
# examiner: Aragorn II Elessar # only required if PhD; otherwise delete or comment out
# This is the YAML (YAML Ain't Markup Language) header that includes 
# metadata used to produce the document. 
# Be careful with spacing in this header!
# Two spaces at the start of the line create indentation,
# which embeds the parameter in a hierarchy.

####################
## Front Matter   ##
####################
# dedication: For my loved ones # If you'd prefer to not include a Dedication, for example, simply delete the section entirely, or silence them (add # before each line). 
resume: | # otherwise known as the abstract
  `r paste(readLines("front-matter/_abstract.Rmd"), collapse = '\n  ')`
acknowledgements: |
  `r paste(readLines("front-matter/_acknowledgements.Rmd"), collapse = '\n  ')`
# abbreviations: "front-matter/abbreviations" # path to .tex file with abbreviations
toc-depth: 6 # depth of heading to include in table of contents
lof: true # list of figures in front matter?
lot: true # list of tables in front matter?
mini-toc: false  # mini-table of contents at start of each chapter? (this just prepares it; you must also add \minitoc after the chapter titles)
mini-lot: false  # mini-list of tables by start of each chapter?
mini-lof: false  # mini-list of figures by start of each chapter?

####################
## Bibliography   ##
####################
bibliography: bib/references.bib #Set your bibliography file here.
bibliography-heading-in-pdf: References
bib-style: authoryear # See https://www.overleaf.com/learn/latex/biblatex_citation_styles for a list of the commonly used built-in citations styles of biblatex.
bib-sorting: nyt #See https://www.overleaf.com/learn/latex/Articles/Getting_started_with_BibLaTeX for different bibliography sorting options.
citeall: true #Set this to true if you want all elements in your .bib file to appear in your bibliography (i.e. all R-packages you used).

#####################
## PDF Formatting  ##
#####################
draft: false # add DRAFT mark in the footer and line numbering?
page-layout: oneside #'oneside' for PDF output (equal margins), 
# or 'twoside' for two-sided binding (mirror margins and blank pages) 
hidelinks: false #if false, the PDF output highlights clickable links with a colored border 
# you will probably want to set this to true for PDF version you wish to physically print
knit: iheiddown::thesis_pdf
#####################
## Output Options  ##
#####################
output: iheiddown::thesis_pdf
link-citations: true
documentclass: book
---

# Preface {.unnumbered}

```{=html}
<!-- 
The {.unnumbered} option here means that the introduction will be 
"Chapter 0." You can also use {-} for no numbers on chapters.
-->
```
<!-- This chunk creates automatically a .bib file to cite the loaded packages in the bibliography. Do not forget to set "citeall" to true in the bibliography section of the YAML header if you want all packages to be cited even if you did not mention them in the body of the text.-->

```{r markdown_step_up, include=FALSE}
knitr::write_bib(c(.packages(), "bookdown"), "bib/packages.bib")
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
library(reticulate)
```

My motivation to write for the topic of media portrayal of asylum seekers (or more formally, non-refoulement claimants) in Hong Kong mainly comes from two sources. On one hand, the salient political affiliation of media outlets in Hong Kong as recorded by @leeChangingPoliticalEconomy2018 has greatly affected how various socio-political issues are framed in the public debate, especially during the 2019 anti-extradition law protest which mobilised millions of Hong Kong citizens to first oppose a law that would have allowed fugitives to be extradited to mainland China and then fight for democracy in the city's political system. As much as these high-profile issues directly relating to the political authority and control over the city by the Beijing Government undoubtedly mark the distinction between pro-Beijing and non-pro-Beijing media outlets in terms of reportage, I suspect that the difference in the narratives by the media outlets in Hong Kong about non-refoulement claimants can also be demarcated based on whether a media outlet is affiliated with the pro-Beijing camp or not.

Indeed, the Hong Kong Government adopts an unwelcoming stance towards foreigners who wish to seek asylum within the city's territory. Apart from completely rejecting the possibility of any refugees being recognised and resettled locally [Immigration Department -@immigrationdepartmentMakingClaimNonrefoulement2021], the Hong Kong Government also becomes more suspicious about the genuineness of non-refoulement claims in recent years as the former Chief Executive *CY Leung* once suggested that Hong Kong leave the UN Convention against Torture (UNCAT) in 2016 to alleviate the so-called "fake refugee" problem [@chengNGOsHitBack2016]. Therefore, pro-Beijing media outlets may echo the Government's unwelcoming stance towards non-refoulement claimants in their reportage to sway the public opinion in favour of more stringent measures, whereas pro-democracy outlets may offer counter-narrative which are more sympathetic towards this group of vulnerable population.

The increasing political pressure faced by alternative media in Hong Kong and, by the beginning of 2022, the closures of several prominent pro-democracy media outlets which had served to be a crucial alternative sources of information about socio-political issues for the public besides foreign news media, further increases the rationale for studying whether the narratives on non-refoulement claimants between pro-Beijing and non-pro-Beijing media outlets may differ in terms of attitudes. This is because if political affiliation does turn out to be an influential factor of predicting the sentiment of news articles about asylum seekers in Hong Kong and pro-Beijing camp newspapers are indeed more negative in their coverage about non-refoulement claimants, then it is likely that the media's narrative on asylum seekers in the city will be increasingly dominated by pro-Beijing media outlets following the dissolution of pro-democracy media outlets. This may then foster a higher degree of hostility against non-refoulement claimants on top of the Hong Kong Government's already unwelcoming asylum seeking policies.

Apart from my research interest in the politics behind the media landscape of Hong Kong, I also took this opportunity to test whether automated approaches can help effectively learn the relationship between a media outlet's political affiliation plus other features derived from the news articles and their sentiments towards asylum seekers. As @vanatteveldtValiditySentimentAnalysis2021 note, automated sentiment analysis for non-English language sources appears to be rarely used and yet, despite some caveats, this method can potentially cope with problems of scaling research on larger dataset faced by manual coding. Given the prominence of text as a major medium of transmitting information to readers in newspapers and the availability of tools and software specifically designed for natural language processing in Chinese, studying whether political affiliations of newspaper outlets may be correlated to the attitudes of the news articles on non-refoulement claimants via machine-learning-based sentiment analysis can help explore whether such automated approaches can also generate reasonable insights from Chinese language text data for social sciences research. If machine learning models perform adequately in learning about the relationships between different features (some of which are created from the text in the articles) and the sentiment of the news articles in this analysis, then this may imply that future social sciences research on textual data (e.g. sentiment analysis) in Chinese language can also benefit from using automated methods to scale on larger datasets, given that nowadays a huge amount of information in textual format is generated each day which will may pose difficulties for manually going through all the entries if the size of a document corpus is sufficiently large.

The process of the research for this thesis was quite long and not without difficulties. First of all, given the vast volume of literature related to the study of asylum seekers based on numerous perspectives and levels of analysis, it was quite easy to get lost while reviewing the literature. In the end, I decided to focus on the literature of how the definition of national identity may affect the perceptions towards immigrants (of which asylum seekers are a subgroup) because of the remarkable ethnic difference between most of the ethnic-Chinese citizens in Hong Kong and non-refoulement claimants. Besides, the political division in Hong Kong is arguably more salient on how the national identity of citizens in Hong Kong should be defined (e.g. whether ethnic Chineseness or civic values should play a larger role in the definition) even though it is equally valid to classify the political parties within each camp according to the more conventional left-right socio-economic dimension [@maPoliticalPartiesElections2012].

The data collection and pre-processing part also took a considerable amount of time. Apart from selecting relevant news articles about non-refoulement claimants published by newspapers in 2019, the unstructured nature of text data also required a lot of steps to transform them into a suitable format for being machine learning model inputs. Moreover, the fact that the downloaded news articles from *Wisenews* database do not come with pre-labelled sentiments also means that it is important to refer to reliable coding scheme to operationalise the dependent variable of this thesis (fortunately, the literature is always here to help). As much as there are numerous performant machine learning models available nowadays, the results will not be very meaningful if the data quality is not optimal. Modelling the data, on the other hand, was a relatively less difficult process than the data pre-processing part.

In any case, this thesis was finally written. This also marks the end of my master's programme at the Graduate Institute. Overall, this was quite an enriching experience. I can't simply describe with words how much I have learnt over the last two years. I believe this experience will be invaluable for my life.
